// flow-typed signature: db823a5c18f54481ff550bd09d7d2ad4
// flow-typed version: <<STUB>>/@app-masters/js-lib_v1.1.24/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@app-masters/js-lib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@app-masters/js-lib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@app-masters/js-lib/dist/appBootstrap' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/dist/dateTime' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/dist/dependencies/flexStorage' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/dist/dependencies/rollbar' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/dist/http' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/dist/httpErrorHandler' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/dist/index' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/dist/jsError' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/dist/notification' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/dist/notificationCordova' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/dist/notificationNative' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/dist/notificationWeb' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/dist/objHandler' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/dist/rollbar' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/dist/storage' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/dist/text' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/dist/version' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/src/appBootstrap' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/src/dateTime' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/src/dependencies/flexStorage' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/src/dependencies/rollbar' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/src/http' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/src/httpErrorHandler' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/src/index' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/src/jsError' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/src/notification' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/src/notificationCordova' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/src/notificationNative' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/src/notificationWeb' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/src/objHandler' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/src/rollbar' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/src/storage' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/src/text' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/src/version' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/test/bootstrap.test' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/test/dateTime.test' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/test/http.test' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/test/localStorageMock' {
  declare module.exports: any;
}

declare module '@app-masters/js-lib/test/testConfig' {
  declare module.exports: any;
}

// Filename aliases
declare module '@app-masters/js-lib/dist/appBootstrap.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/dist/appBootstrap'>;
}
declare module '@app-masters/js-lib/dist/dateTime.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/dist/dateTime'>;
}
declare module '@app-masters/js-lib/dist/dependencies/flexStorage.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/dist/dependencies/flexStorage'>;
}
declare module '@app-masters/js-lib/dist/dependencies/rollbar.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/dist/dependencies/rollbar'>;
}
declare module '@app-masters/js-lib/dist/http.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/dist/http'>;
}
declare module '@app-masters/js-lib/dist/httpErrorHandler.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/dist/httpErrorHandler'>;
}
declare module '@app-masters/js-lib/dist/index.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/dist/index'>;
}
declare module '@app-masters/js-lib/dist/jsError.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/dist/jsError'>;
}
declare module '@app-masters/js-lib/dist/notification.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/dist/notification'>;
}
declare module '@app-masters/js-lib/dist/notificationCordova.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/dist/notificationCordova'>;
}
declare module '@app-masters/js-lib/dist/notificationNative.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/dist/notificationNative'>;
}
declare module '@app-masters/js-lib/dist/notificationWeb.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/dist/notificationWeb'>;
}
declare module '@app-masters/js-lib/dist/objHandler.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/dist/objHandler'>;
}
declare module '@app-masters/js-lib/dist/rollbar.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/dist/rollbar'>;
}
declare module '@app-masters/js-lib/dist/storage.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/dist/storage'>;
}
declare module '@app-masters/js-lib/dist/text.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/dist/text'>;
}
declare module '@app-masters/js-lib/dist/version.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/dist/version'>;
}
declare module '@app-masters/js-lib/index' {
  declare module.exports: $Exports<'@app-masters/js-lib'>;
}
declare module '@app-masters/js-lib/index.js' {
  declare module.exports: $Exports<'@app-masters/js-lib'>;
}
declare module '@app-masters/js-lib/src/appBootstrap.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/src/appBootstrap'>;
}
declare module '@app-masters/js-lib/src/dateTime.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/src/dateTime'>;
}
declare module '@app-masters/js-lib/src/dependencies/flexStorage.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/src/dependencies/flexStorage'>;
}
declare module '@app-masters/js-lib/src/dependencies/rollbar.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/src/dependencies/rollbar'>;
}
declare module '@app-masters/js-lib/src/http.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/src/http'>;
}
declare module '@app-masters/js-lib/src/httpErrorHandler.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/src/httpErrorHandler'>;
}
declare module '@app-masters/js-lib/src/index.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/src/index'>;
}
declare module '@app-masters/js-lib/src/jsError.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/src/jsError'>;
}
declare module '@app-masters/js-lib/src/notification.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/src/notification'>;
}
declare module '@app-masters/js-lib/src/notificationCordova.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/src/notificationCordova'>;
}
declare module '@app-masters/js-lib/src/notificationNative.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/src/notificationNative'>;
}
declare module '@app-masters/js-lib/src/notificationWeb.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/src/notificationWeb'>;
}
declare module '@app-masters/js-lib/src/objHandler.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/src/objHandler'>;
}
declare module '@app-masters/js-lib/src/rollbar.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/src/rollbar'>;
}
declare module '@app-masters/js-lib/src/storage.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/src/storage'>;
}
declare module '@app-masters/js-lib/src/text.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/src/text'>;
}
declare module '@app-masters/js-lib/src/version.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/src/version'>;
}
declare module '@app-masters/js-lib/test/bootstrap.test.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/test/bootstrap.test'>;
}
declare module '@app-masters/js-lib/test/dateTime.test.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/test/dateTime.test'>;
}
declare module '@app-masters/js-lib/test/http.test.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/test/http.test'>;
}
declare module '@app-masters/js-lib/test/localStorageMock.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/test/localStorageMock'>;
}
declare module '@app-masters/js-lib/test/testConfig.js' {
  declare module.exports: $Exports<'@app-masters/js-lib/test/testConfig'>;
}
