// flow-typed signature: 1d47116953c13ec121f8437c859f2351
// flow-typed version: <<STUB>>/@app-masters/react-cloudinary-uploader_v0.1.2/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@app-masters/react-cloudinary-uploader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@app-masters/react-cloudinary-uploader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@app-masters/react-cloudinary-uploader/dist/index' {
  declare module.exports: any;
}

declare module '@app-masters/react-cloudinary-uploader/dist/ReactCloudinaryUploader' {
  declare module.exports: any;
}

declare module '@app-masters/react-cloudinary-uploader/src/index' {
  declare module.exports: any;
}

declare module '@app-masters/react-cloudinary-uploader/src/ReactCloudinaryUploader' {
  declare module.exports: any;
}

// Filename aliases
declare module '@app-masters/react-cloudinary-uploader/dist/index.js' {
  declare module.exports: $Exports<'@app-masters/react-cloudinary-uploader/dist/index'>;
}
declare module '@app-masters/react-cloudinary-uploader/dist/ReactCloudinaryUploader.js' {
  declare module.exports: $Exports<'@app-masters/react-cloudinary-uploader/dist/ReactCloudinaryUploader'>;
}
declare module '@app-masters/react-cloudinary-uploader/src/index.js' {
  declare module.exports: $Exports<'@app-masters/react-cloudinary-uploader/src/index'>;
}
declare module '@app-masters/react-cloudinary-uploader/src/ReactCloudinaryUploader.js' {
  declare module.exports: $Exports<'@app-masters/react-cloudinary-uploader/src/ReactCloudinaryUploader'>;
}
