// flow-typed signature: f9bdc4f629e0cb3219ca0997eee71bce
// flow-typed version: <<STUB>>/connect-session-sequelize_v^5.2.1/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connect-session-sequelize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'connect-session-sequelize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'connect-session-sequelize/lib/connect-session-sequelize' {
  declare module.exports: any;
}

declare module 'connect-session-sequelize/lib/model' {
  declare module.exports: any;
}

// Filename aliases
declare module 'connect-session-sequelize/index' {
  declare module.exports: $Exports<'connect-session-sequelize'>;
}
declare module 'connect-session-sequelize/index.js' {
  declare module.exports: $Exports<'connect-session-sequelize'>;
}
declare module 'connect-session-sequelize/lib/connect-session-sequelize.js' {
  declare module.exports: $Exports<'connect-session-sequelize/lib/connect-session-sequelize'>;
}
declare module 'connect-session-sequelize/lib/model.js' {
  declare module.exports: $Exports<'connect-session-sequelize/lib/model'>;
}
