// flow-typed signature: 4dcccac54760294da17de9c1ad6b4129
// flow-typed version: <<STUB>>/cron_v1.3.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cron/lib/cron' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cron/lib/cron.js' {
  declare module.exports: $Exports<'cron/lib/cron'>;
}
