// flow-typed signature: a8abd354cae0c46caf6cdf3c8694cac7
// flow-typed version: <<STUB>>/finale-rest_v0.1.3/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'finale-rest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'finale-rest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'finale-rest/lib/associations/belongs-to-many' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/associations/belongs-to' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/associations/has-many' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/associations/has-one' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/Controllers/base' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/Controllers/create' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/Controllers/delete' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/Controllers/index' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/Controllers/list' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/Controllers/read' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/Controllers/update' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/Endpoint' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/Errors' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/index' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/Resource' {
  declare module.exports: any;
}

declare module 'finale-rest/lib/util' {
  declare module.exports: any;
}

declare module 'finale-rest/tests/associations/belongs-to-many.test' {
  declare module.exports: any;
}

declare module 'finale-rest/tests/associations/belongs-to.test' {
  declare module.exports: any;
}

declare module 'finale-rest/tests/associations/has-many.test' {
  declare module.exports: any;
}

declare module 'finale-rest/tests/associations/has-one.test' {
  declare module.exports: any;
}

declare module 'finale-rest/tests/epilogue.test' {
  declare module.exports: any;
}

declare module 'finale-rest/tests/issues/107.test' {
  declare module.exports: any;
}

declare module 'finale-rest/tests/issues/117.test' {
  declare module.exports: any;
}

declare module 'finale-rest/tests/issues/161.test' {
  declare module.exports: any;
}

declare module 'finale-rest/tests/milestones/data/test-middleware-before-after' {
  declare module.exports: any;
}

declare module 'finale-rest/tests/milestones/data/test-middleware' {
  declare module.exports: any;
}

declare module 'finale-rest/tests/milestones/middleware.test' {
  declare module.exports: any;
}

declare module 'finale-rest/tests/milestones/milestones.test' {
  declare module.exports: any;
}

declare module 'finale-rest/tests/resource/hooks.test' {
  declare module.exports: any;
}

declare module 'finale-rest/tests/resource/pagination.test' {
  declare module.exports: any;
}

declare module 'finale-rest/tests/resource/resource.test' {
  declare module.exports: any;
}

declare module 'finale-rest/tests/resource/search.test' {
  declare module.exports: any;
}

declare module 'finale-rest/tests/resource/sort.test' {
  declare module.exports: any;
}

declare module 'finale-rest/tests/resource/updatemethod.test' {
  declare module.exports: any;
}

declare module 'finale-rest/tests/support' {
  declare module.exports: any;
}

declare module 'finale-rest/tests/util.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'finale-rest/lib/associations/belongs-to-many.js' {
  declare module.exports: $Exports<'finale-rest/lib/associations/belongs-to-many'>;
}
declare module 'finale-rest/lib/associations/belongs-to.js' {
  declare module.exports: $Exports<'finale-rest/lib/associations/belongs-to'>;
}
declare module 'finale-rest/lib/associations/has-many.js' {
  declare module.exports: $Exports<'finale-rest/lib/associations/has-many'>;
}
declare module 'finale-rest/lib/associations/has-one.js' {
  declare module.exports: $Exports<'finale-rest/lib/associations/has-one'>;
}
declare module 'finale-rest/lib/Controllers/base.js' {
  declare module.exports: $Exports<'finale-rest/lib/Controllers/base'>;
}
declare module 'finale-rest/lib/Controllers/create.js' {
  declare module.exports: $Exports<'finale-rest/lib/Controllers/create'>;
}
declare module 'finale-rest/lib/Controllers/delete.js' {
  declare module.exports: $Exports<'finale-rest/lib/Controllers/delete'>;
}
declare module 'finale-rest/lib/Controllers/index.js' {
  declare module.exports: $Exports<'finale-rest/lib/Controllers/index'>;
}
declare module 'finale-rest/lib/Controllers/list.js' {
  declare module.exports: $Exports<'finale-rest/lib/Controllers/list'>;
}
declare module 'finale-rest/lib/Controllers/read.js' {
  declare module.exports: $Exports<'finale-rest/lib/Controllers/read'>;
}
declare module 'finale-rest/lib/Controllers/update.js' {
  declare module.exports: $Exports<'finale-rest/lib/Controllers/update'>;
}
declare module 'finale-rest/lib/Endpoint.js' {
  declare module.exports: $Exports<'finale-rest/lib/Endpoint'>;
}
declare module 'finale-rest/lib/Errors.js' {
  declare module.exports: $Exports<'finale-rest/lib/Errors'>;
}
declare module 'finale-rest/lib/index.js' {
  declare module.exports: $Exports<'finale-rest/lib/index'>;
}
declare module 'finale-rest/lib/Resource.js' {
  declare module.exports: $Exports<'finale-rest/lib/Resource'>;
}
declare module 'finale-rest/lib/util.js' {
  declare module.exports: $Exports<'finale-rest/lib/util'>;
}
declare module 'finale-rest/tests/associations/belongs-to-many.test.js' {
  declare module.exports: $Exports<'finale-rest/tests/associations/belongs-to-many.test'>;
}
declare module 'finale-rest/tests/associations/belongs-to.test.js' {
  declare module.exports: $Exports<'finale-rest/tests/associations/belongs-to.test'>;
}
declare module 'finale-rest/tests/associations/has-many.test.js' {
  declare module.exports: $Exports<'finale-rest/tests/associations/has-many.test'>;
}
declare module 'finale-rest/tests/associations/has-one.test.js' {
  declare module.exports: $Exports<'finale-rest/tests/associations/has-one.test'>;
}
declare module 'finale-rest/tests/epilogue.test.js' {
  declare module.exports: $Exports<'finale-rest/tests/epilogue.test'>;
}
declare module 'finale-rest/tests/issues/107.test.js' {
  declare module.exports: $Exports<'finale-rest/tests/issues/107.test'>;
}
declare module 'finale-rest/tests/issues/117.test.js' {
  declare module.exports: $Exports<'finale-rest/tests/issues/117.test'>;
}
declare module 'finale-rest/tests/issues/161.test.js' {
  declare module.exports: $Exports<'finale-rest/tests/issues/161.test'>;
}
declare module 'finale-rest/tests/milestones/data/test-middleware-before-after.js' {
  declare module.exports: $Exports<'finale-rest/tests/milestones/data/test-middleware-before-after'>;
}
declare module 'finale-rest/tests/milestones/data/test-middleware.js' {
  declare module.exports: $Exports<'finale-rest/tests/milestones/data/test-middleware'>;
}
declare module 'finale-rest/tests/milestones/middleware.test.js' {
  declare module.exports: $Exports<'finale-rest/tests/milestones/middleware.test'>;
}
declare module 'finale-rest/tests/milestones/milestones.test.js' {
  declare module.exports: $Exports<'finale-rest/tests/milestones/milestones.test'>;
}
declare module 'finale-rest/tests/resource/hooks.test.js' {
  declare module.exports: $Exports<'finale-rest/tests/resource/hooks.test'>;
}
declare module 'finale-rest/tests/resource/pagination.test.js' {
  declare module.exports: $Exports<'finale-rest/tests/resource/pagination.test'>;
}
declare module 'finale-rest/tests/resource/resource.test.js' {
  declare module.exports: $Exports<'finale-rest/tests/resource/resource.test'>;
}
declare module 'finale-rest/tests/resource/search.test.js' {
  declare module.exports: $Exports<'finale-rest/tests/resource/search.test'>;
}
declare module 'finale-rest/tests/resource/sort.test.js' {
  declare module.exports: $Exports<'finale-rest/tests/resource/sort.test'>;
}
declare module 'finale-rest/tests/resource/updatemethod.test.js' {
  declare module.exports: $Exports<'finale-rest/tests/resource/updatemethod.test'>;
}
declare module 'finale-rest/tests/support.js' {
  declare module.exports: $Exports<'finale-rest/tests/support'>;
}
declare module 'finale-rest/tests/util.test.js' {
  declare module.exports: $Exports<'finale-rest/tests/util.test'>;
}
