// flow-typed signature: 075afba2ccfd3c269aefd1068e721df0
// flow-typed version: <<STUB>>/moip-sdk-node_v^1.2.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moip-sdk-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'moip-sdk-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'moip-sdk-node/dist/api' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/client/api_assinaturas' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/client/api' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/client/authorization' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/client/endpoints' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/client/environment' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/client/index' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/client/resources' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/index' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/resources/account' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/resources/bankAccount' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/resources/connect' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/resources/coupon' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/resources/customer' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/resources/escrow' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/resources/multiorder' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/resources/multipayment' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/resources/notification' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/resources/order' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/resources/payment' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/resources/plan' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/resources/refund' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/resources/subscriber' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/resources/subscription' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/resources/webhook' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/account.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/bankAccount.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/config/auth' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/config/basicAuth' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/connect.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/coupon.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/customer.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/escrow.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/index' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/notification.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/order.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/payment.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/plan.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/refund.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/schemas/account' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/schemas/bankAccount' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/schemas/coupon' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/schemas/creditCard' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/schemas/customer' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/schemas/notification' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/schemas/order' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/schemas/payment' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/schemas/paymentWithEscrow' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/schemas/plan' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/schemas/subscriber' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/schemas/subscription' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/subscriber.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/subscription.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/dist/specs/webhook.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/lib/client/api_assinaturas' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/lib/client/api' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/lib/client/endpoints' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/lib/client/index' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/lib/client/resources' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/lib/index' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/lib/resources/account' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/lib/resources/bankAccount' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/lib/resources/connect' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/lib/resources/coupon' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/lib/resources/customer' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/lib/resources/escrow' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/lib/resources/multiorder' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/lib/resources/multipayment' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/lib/resources/notification' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/lib/resources/order' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/lib/resources/payment' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/lib/resources/plan' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/lib/resources/refund' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/lib/resources/subscriber' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/lib/resources/subscription' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/lib/resources/webhook' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/account.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/bankAccount.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/config/auth' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/config/basicAuth' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/connect.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/coupon.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/customer.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/escrow.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/index' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/multiorder.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/multipayment.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/notification.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/order.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/payment.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/plan.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/refund.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/schemas/account' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/schemas/bankAccount' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/schemas/coupon' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/schemas/creditCard' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/schemas/customer' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/schemas/multiorder' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/schemas/notification' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/schemas/order' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/schemas/payment' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/schemas/paymentWithEscrow' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/schemas/plan' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/schemas/subscriber' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/schemas/subscription' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/subscriber.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/subscription.spec' {
  declare module.exports: any;
}

declare module 'moip-sdk-node/test/webhook.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'moip-sdk-node/dist/api.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/api'>;
}
declare module 'moip-sdk-node/dist/client/api_assinaturas.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/client/api_assinaturas'>;
}
declare module 'moip-sdk-node/dist/client/api.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/client/api'>;
}
declare module 'moip-sdk-node/dist/client/authorization.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/client/authorization'>;
}
declare module 'moip-sdk-node/dist/client/endpoints.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/client/endpoints'>;
}
declare module 'moip-sdk-node/dist/client/environment.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/client/environment'>;
}
declare module 'moip-sdk-node/dist/client/index.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/client/index'>;
}
declare module 'moip-sdk-node/dist/client/resources.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/client/resources'>;
}
declare module 'moip-sdk-node/dist/index.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/index'>;
}
declare module 'moip-sdk-node/dist/resources/account.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/resources/account'>;
}
declare module 'moip-sdk-node/dist/resources/bankAccount.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/resources/bankAccount'>;
}
declare module 'moip-sdk-node/dist/resources/connect.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/resources/connect'>;
}
declare module 'moip-sdk-node/dist/resources/coupon.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/resources/coupon'>;
}
declare module 'moip-sdk-node/dist/resources/customer.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/resources/customer'>;
}
declare module 'moip-sdk-node/dist/resources/escrow.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/resources/escrow'>;
}
declare module 'moip-sdk-node/dist/resources/multiorder.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/resources/multiorder'>;
}
declare module 'moip-sdk-node/dist/resources/multipayment.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/resources/multipayment'>;
}
declare module 'moip-sdk-node/dist/resources/notification.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/resources/notification'>;
}
declare module 'moip-sdk-node/dist/resources/order.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/resources/order'>;
}
declare module 'moip-sdk-node/dist/resources/payment.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/resources/payment'>;
}
declare module 'moip-sdk-node/dist/resources/plan.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/resources/plan'>;
}
declare module 'moip-sdk-node/dist/resources/refund.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/resources/refund'>;
}
declare module 'moip-sdk-node/dist/resources/subscriber.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/resources/subscriber'>;
}
declare module 'moip-sdk-node/dist/resources/subscription.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/resources/subscription'>;
}
declare module 'moip-sdk-node/dist/resources/webhook.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/resources/webhook'>;
}
declare module 'moip-sdk-node/dist/specs/account.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/account.spec'>;
}
declare module 'moip-sdk-node/dist/specs/bankAccount.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/bankAccount.spec'>;
}
declare module 'moip-sdk-node/dist/specs/config/auth.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/config/auth'>;
}
declare module 'moip-sdk-node/dist/specs/config/basicAuth.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/config/basicAuth'>;
}
declare module 'moip-sdk-node/dist/specs/connect.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/connect.spec'>;
}
declare module 'moip-sdk-node/dist/specs/coupon.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/coupon.spec'>;
}
declare module 'moip-sdk-node/dist/specs/customer.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/customer.spec'>;
}
declare module 'moip-sdk-node/dist/specs/escrow.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/escrow.spec'>;
}
declare module 'moip-sdk-node/dist/specs/index.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/index'>;
}
declare module 'moip-sdk-node/dist/specs/notification.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/notification.spec'>;
}
declare module 'moip-sdk-node/dist/specs/order.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/order.spec'>;
}
declare module 'moip-sdk-node/dist/specs/payment.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/payment.spec'>;
}
declare module 'moip-sdk-node/dist/specs/plan.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/plan.spec'>;
}
declare module 'moip-sdk-node/dist/specs/refund.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/refund.spec'>;
}
declare module 'moip-sdk-node/dist/specs/schemas/account.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/schemas/account'>;
}
declare module 'moip-sdk-node/dist/specs/schemas/bankAccount.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/schemas/bankAccount'>;
}
declare module 'moip-sdk-node/dist/specs/schemas/coupon.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/schemas/coupon'>;
}
declare module 'moip-sdk-node/dist/specs/schemas/creditCard.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/schemas/creditCard'>;
}
declare module 'moip-sdk-node/dist/specs/schemas/customer.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/schemas/customer'>;
}
declare module 'moip-sdk-node/dist/specs/schemas/notification.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/schemas/notification'>;
}
declare module 'moip-sdk-node/dist/specs/schemas/order.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/schemas/order'>;
}
declare module 'moip-sdk-node/dist/specs/schemas/payment.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/schemas/payment'>;
}
declare module 'moip-sdk-node/dist/specs/schemas/paymentWithEscrow.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/schemas/paymentWithEscrow'>;
}
declare module 'moip-sdk-node/dist/specs/schemas/plan.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/schemas/plan'>;
}
declare module 'moip-sdk-node/dist/specs/schemas/subscriber.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/schemas/subscriber'>;
}
declare module 'moip-sdk-node/dist/specs/schemas/subscription.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/schemas/subscription'>;
}
declare module 'moip-sdk-node/dist/specs/subscriber.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/subscriber.spec'>;
}
declare module 'moip-sdk-node/dist/specs/subscription.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/subscription.spec'>;
}
declare module 'moip-sdk-node/dist/specs/webhook.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/dist/specs/webhook.spec'>;
}
declare module 'moip-sdk-node/index' {
  declare module.exports: $Exports<'moip-sdk-node'>;
}
declare module 'moip-sdk-node/index.js' {
  declare module.exports: $Exports<'moip-sdk-node'>;
}
declare module 'moip-sdk-node/lib/client/api_assinaturas.js' {
  declare module.exports: $Exports<'moip-sdk-node/lib/client/api_assinaturas'>;
}
declare module 'moip-sdk-node/lib/client/api.js' {
  declare module.exports: $Exports<'moip-sdk-node/lib/client/api'>;
}
declare module 'moip-sdk-node/lib/client/endpoints.js' {
  declare module.exports: $Exports<'moip-sdk-node/lib/client/endpoints'>;
}
declare module 'moip-sdk-node/lib/client/index.js' {
  declare module.exports: $Exports<'moip-sdk-node/lib/client/index'>;
}
declare module 'moip-sdk-node/lib/client/resources.js' {
  declare module.exports: $Exports<'moip-sdk-node/lib/client/resources'>;
}
declare module 'moip-sdk-node/lib/index.js' {
  declare module.exports: $Exports<'moip-sdk-node/lib/index'>;
}
declare module 'moip-sdk-node/lib/resources/account.js' {
  declare module.exports: $Exports<'moip-sdk-node/lib/resources/account'>;
}
declare module 'moip-sdk-node/lib/resources/bankAccount.js' {
  declare module.exports: $Exports<'moip-sdk-node/lib/resources/bankAccount'>;
}
declare module 'moip-sdk-node/lib/resources/connect.js' {
  declare module.exports: $Exports<'moip-sdk-node/lib/resources/connect'>;
}
declare module 'moip-sdk-node/lib/resources/coupon.js' {
  declare module.exports: $Exports<'moip-sdk-node/lib/resources/coupon'>;
}
declare module 'moip-sdk-node/lib/resources/customer.js' {
  declare module.exports: $Exports<'moip-sdk-node/lib/resources/customer'>;
}
declare module 'moip-sdk-node/lib/resources/escrow.js' {
  declare module.exports: $Exports<'moip-sdk-node/lib/resources/escrow'>;
}
declare module 'moip-sdk-node/lib/resources/multiorder.js' {
  declare module.exports: $Exports<'moip-sdk-node/lib/resources/multiorder'>;
}
declare module 'moip-sdk-node/lib/resources/multipayment.js' {
  declare module.exports: $Exports<'moip-sdk-node/lib/resources/multipayment'>;
}
declare module 'moip-sdk-node/lib/resources/notification.js' {
  declare module.exports: $Exports<'moip-sdk-node/lib/resources/notification'>;
}
declare module 'moip-sdk-node/lib/resources/order.js' {
  declare module.exports: $Exports<'moip-sdk-node/lib/resources/order'>;
}
declare module 'moip-sdk-node/lib/resources/payment.js' {
  declare module.exports: $Exports<'moip-sdk-node/lib/resources/payment'>;
}
declare module 'moip-sdk-node/lib/resources/plan.js' {
  declare module.exports: $Exports<'moip-sdk-node/lib/resources/plan'>;
}
declare module 'moip-sdk-node/lib/resources/refund.js' {
  declare module.exports: $Exports<'moip-sdk-node/lib/resources/refund'>;
}
declare module 'moip-sdk-node/lib/resources/subscriber.js' {
  declare module.exports: $Exports<'moip-sdk-node/lib/resources/subscriber'>;
}
declare module 'moip-sdk-node/lib/resources/subscription.js' {
  declare module.exports: $Exports<'moip-sdk-node/lib/resources/subscription'>;
}
declare module 'moip-sdk-node/lib/resources/webhook.js' {
  declare module.exports: $Exports<'moip-sdk-node/lib/resources/webhook'>;
}
declare module 'moip-sdk-node/test/account.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/account.spec'>;
}
declare module 'moip-sdk-node/test/bankAccount.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/bankAccount.spec'>;
}
declare module 'moip-sdk-node/test/config/auth.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/config/auth'>;
}
declare module 'moip-sdk-node/test/config/basicAuth.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/config/basicAuth'>;
}
declare module 'moip-sdk-node/test/connect.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/connect.spec'>;
}
declare module 'moip-sdk-node/test/coupon.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/coupon.spec'>;
}
declare module 'moip-sdk-node/test/customer.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/customer.spec'>;
}
declare module 'moip-sdk-node/test/escrow.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/escrow.spec'>;
}
declare module 'moip-sdk-node/test/index.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/index'>;
}
declare module 'moip-sdk-node/test/multiorder.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/multiorder.spec'>;
}
declare module 'moip-sdk-node/test/multipayment.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/multipayment.spec'>;
}
declare module 'moip-sdk-node/test/notification.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/notification.spec'>;
}
declare module 'moip-sdk-node/test/order.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/order.spec'>;
}
declare module 'moip-sdk-node/test/payment.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/payment.spec'>;
}
declare module 'moip-sdk-node/test/plan.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/plan.spec'>;
}
declare module 'moip-sdk-node/test/refund.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/refund.spec'>;
}
declare module 'moip-sdk-node/test/schemas/account.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/schemas/account'>;
}
declare module 'moip-sdk-node/test/schemas/bankAccount.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/schemas/bankAccount'>;
}
declare module 'moip-sdk-node/test/schemas/coupon.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/schemas/coupon'>;
}
declare module 'moip-sdk-node/test/schemas/creditCard.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/schemas/creditCard'>;
}
declare module 'moip-sdk-node/test/schemas/customer.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/schemas/customer'>;
}
declare module 'moip-sdk-node/test/schemas/multiorder.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/schemas/multiorder'>;
}
declare module 'moip-sdk-node/test/schemas/notification.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/schemas/notification'>;
}
declare module 'moip-sdk-node/test/schemas/order.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/schemas/order'>;
}
declare module 'moip-sdk-node/test/schemas/payment.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/schemas/payment'>;
}
declare module 'moip-sdk-node/test/schemas/paymentWithEscrow.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/schemas/paymentWithEscrow'>;
}
declare module 'moip-sdk-node/test/schemas/plan.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/schemas/plan'>;
}
declare module 'moip-sdk-node/test/schemas/subscriber.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/schemas/subscriber'>;
}
declare module 'moip-sdk-node/test/schemas/subscription.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/schemas/subscription'>;
}
declare module 'moip-sdk-node/test/subscriber.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/subscriber.spec'>;
}
declare module 'moip-sdk-node/test/subscription.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/subscription.spec'>;
}
declare module 'moip-sdk-node/test/webhook.spec.js' {
  declare module.exports: $Exports<'moip-sdk-node/test/webhook.spec'>;
}
