// flow-typed signature: 5a0bb7be8f7cdf129d7a02f2674dcc0f
// flow-typed version: <<STUB>>/mongoose-delete_v0.4.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongoose-delete'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongoose-delete' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongoose-delete/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongoose-delete/index' {
  declare module.exports: $Exports<'mongoose-delete'>;
}
declare module 'mongoose-delete/index.js' {
  declare module.exports: $Exports<'mongoose-delete'>;
}
declare module 'mongoose-delete/test/index.js' {
  declare module.exports: $Exports<'mongoose-delete/test/index'>;
}
