// flow-typed signature: e8b2430833804917a663cc39735e235c
// flow-typed version: <<STUB>>/mongoose-geojson-schema_v2.1.2/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongoose-geojson-schema'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongoose-geojson-schema' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongoose-geojson-schema/Gruntfile' {
  declare module.exports: any;
}

declare module 'mongoose-geojson-schema/test/GeoJSON.integration' {
  declare module.exports: any;
}

declare module 'mongoose-geojson-schema/test/test.model' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongoose-geojson-schema/Gruntfile.js' {
  declare module.exports: $Exports<'mongoose-geojson-schema/Gruntfile'>;
}
declare module 'mongoose-geojson-schema/index' {
  declare module.exports: $Exports<'mongoose-geojson-schema'>;
}
declare module 'mongoose-geojson-schema/index.js' {
  declare module.exports: $Exports<'mongoose-geojson-schema'>;
}
declare module 'mongoose-geojson-schema/test/GeoJSON.integration.js' {
  declare module.exports: $Exports<'mongoose-geojson-schema/test/GeoJSON.integration'>;
}
declare module 'mongoose-geojson-schema/test/test.model.js' {
  declare module.exports: $Exports<'mongoose-geojson-schema/test/test.model'>;
}
