// flow-typed signature: 1589d13bcf802dfbb9f3d1c20dfc1c7b
// flow-typed version: <<STUB>>/node-restful_v0.2.6/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-restful'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-restful' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-restful/examples/movies/index' {
  declare module.exports: any;
}

declare module 'node-restful/examples/notes' {
  declare module.exports: any;
}

declare module 'node-restful/examples/notes/index' {
  declare module.exports: any;
}

declare module 'node-restful/examples/notes/models/index' {
  declare module.exports: any;
}

declare module 'node-restful/examples/notes/models/note' {
  declare module.exports: any;
}

declare module 'node-restful/examples/notes/models/user' {
  declare module.exports: any;
}

declare module 'node-restful/examples/notes/routes/user' {
  declare module.exports: any;
}

declare module 'node-restful/lib/handlers' {
  declare module.exports: any;
}

declare module 'node-restful/lib/model' {
  declare module.exports: any;
}

declare module 'node-restful/lib/restful' {
  declare module.exports: any;
}

declare module 'node-restful/test/fixtures/config' {
  declare module.exports: any;
}

declare module 'node-restful/test/fixtures/data' {
  declare module.exports: any;
}

declare module 'node-restful/test/model.chainable' {
  declare module.exports: any;
}

declare module 'node-restful/test/model.excludes' {
  declare module.exports: any;
}

declare module 'node-restful/test/model.filters' {
  declare module.exports: any;
}

declare module 'node-restful/test/model.handle' {
  declare module.exports: any;
}

declare module 'node-restful/test/model.hooks' {
  declare module.exports: any;
}

declare module 'node-restful/test/model' {
  declare module.exports: any;
}

declare module 'node-restful/test/model.template' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-restful/examples/movies/index.js' {
  declare module.exports: $Exports<'node-restful/examples/movies/index'>;
}
declare module 'node-restful/examples/notes.js' {
  declare module.exports: $Exports<'node-restful/examples/notes'>;
}
declare module 'node-restful/examples/notes/index.js' {
  declare module.exports: $Exports<'node-restful/examples/notes/index'>;
}
declare module 'node-restful/examples/notes/models/index.js' {
  declare module.exports: $Exports<'node-restful/examples/notes/models/index'>;
}
declare module 'node-restful/examples/notes/models/note.js' {
  declare module.exports: $Exports<'node-restful/examples/notes/models/note'>;
}
declare module 'node-restful/examples/notes/models/user.js' {
  declare module.exports: $Exports<'node-restful/examples/notes/models/user'>;
}
declare module 'node-restful/examples/notes/routes/user.js' {
  declare module.exports: $Exports<'node-restful/examples/notes/routes/user'>;
}
declare module 'node-restful/index' {
  declare module.exports: $Exports<'node-restful'>;
}
declare module 'node-restful/index.js' {
  declare module.exports: $Exports<'node-restful'>;
}
declare module 'node-restful/lib/handlers.js' {
  declare module.exports: $Exports<'node-restful/lib/handlers'>;
}
declare module 'node-restful/lib/model.js' {
  declare module.exports: $Exports<'node-restful/lib/model'>;
}
declare module 'node-restful/lib/restful.js' {
  declare module.exports: $Exports<'node-restful/lib/restful'>;
}
declare module 'node-restful/test/fixtures/config.js' {
  declare module.exports: $Exports<'node-restful/test/fixtures/config'>;
}
declare module 'node-restful/test/fixtures/data.js' {
  declare module.exports: $Exports<'node-restful/test/fixtures/data'>;
}
declare module 'node-restful/test/model.chainable.js' {
  declare module.exports: $Exports<'node-restful/test/model.chainable'>;
}
declare module 'node-restful/test/model.excludes.js' {
  declare module.exports: $Exports<'node-restful/test/model.excludes'>;
}
declare module 'node-restful/test/model.filters.js' {
  declare module.exports: $Exports<'node-restful/test/model.filters'>;
}
declare module 'node-restful/test/model.handle.js' {
  declare module.exports: $Exports<'node-restful/test/model.handle'>;
}
declare module 'node-restful/test/model.hooks.js' {
  declare module.exports: $Exports<'node-restful/test/model.hooks'>;
}
declare module 'node-restful/test/model.js' {
  declare module.exports: $Exports<'node-restful/test/model'>;
}
declare module 'node-restful/test/model.template.js' {
  declare module.exports: $Exports<'node-restful/test/model.template'>;
}
