// flow-typed signature: 8f141dcd434377400a1614d6389039f3
// flow-typed version: <<STUB>>/react-places-autocomplete_v^7.1.1/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-places-autocomplete'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-places-autocomplete' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-places-autocomplete/dist/helpers' {
  declare module.exports: any;
}

declare module 'react-places-autocomplete/dist/index' {
  declare module.exports: any;
}

declare module 'react-places-autocomplete/dist/index.umd' {
  declare module.exports: any;
}

declare module 'react-places-autocomplete/dist/index.umd.min' {
  declare module.exports: any;
}

declare module 'react-places-autocomplete/dist/PlacesAutocomplete' {
  declare module.exports: any;
}

declare module 'react-places-autocomplete/dist/tests/childrenProp.test' {
  declare module.exports: any;
}

declare module 'react-places-autocomplete/dist/tests/helpers.test' {
  declare module.exports: any;
}

declare module 'react-places-autocomplete/dist/tests/helpers/googlePayloads' {
  declare module.exports: any;
}

declare module 'react-places-autocomplete/dist/tests/helpers/jestSetup' {
  declare module.exports: any;
}

declare module 'react-places-autocomplete/dist/tests/helpers/setup' {
  declare module.exports: any;
}

declare module 'react-places-autocomplete/dist/tests/helpers/testHelpers' {
  declare module.exports: any;
}

declare module 'react-places-autocomplete/dist/tests/initialRender.test' {
  declare module.exports: any;
}

declare module 'react-places-autocomplete/dist/tests/keyboardEvents.test' {
  declare module.exports: any;
}

declare module 'react-places-autocomplete/dist/tests/mouseEvents.test' {
  declare module.exports: any;
}

declare module 'react-places-autocomplete/dist/tests/onChangeProp.test' {
  declare module.exports: any;
}

declare module 'react-places-autocomplete/dist/tests/onSelectProp.test' {
  declare module.exports: any;
}

declare module 'react-places-autocomplete/dist/tests/utils.test' {
  declare module.exports: any;
}

declare module 'react-places-autocomplete/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-places-autocomplete/dist/helpers.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/helpers'>;
}
declare module 'react-places-autocomplete/dist/index.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/index'>;
}
declare module 'react-places-autocomplete/dist/index.umd.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/index.umd'>;
}
declare module 'react-places-autocomplete/dist/index.umd.min.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/index.umd.min'>;
}
declare module 'react-places-autocomplete/dist/PlacesAutocomplete.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/PlacesAutocomplete'>;
}
declare module 'react-places-autocomplete/dist/tests/childrenProp.test.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/tests/childrenProp.test'>;
}
declare module 'react-places-autocomplete/dist/tests/helpers.test.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/tests/helpers.test'>;
}
declare module 'react-places-autocomplete/dist/tests/helpers/googlePayloads.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/tests/helpers/googlePayloads'>;
}
declare module 'react-places-autocomplete/dist/tests/helpers/jestSetup.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/tests/helpers/jestSetup'>;
}
declare module 'react-places-autocomplete/dist/tests/helpers/setup.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/tests/helpers/setup'>;
}
declare module 'react-places-autocomplete/dist/tests/helpers/testHelpers.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/tests/helpers/testHelpers'>;
}
declare module 'react-places-autocomplete/dist/tests/initialRender.test.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/tests/initialRender.test'>;
}
declare module 'react-places-autocomplete/dist/tests/keyboardEvents.test.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/tests/keyboardEvents.test'>;
}
declare module 'react-places-autocomplete/dist/tests/mouseEvents.test.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/tests/mouseEvents.test'>;
}
declare module 'react-places-autocomplete/dist/tests/onChangeProp.test.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/tests/onChangeProp.test'>;
}
declare module 'react-places-autocomplete/dist/tests/onSelectProp.test.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/tests/onSelectProp.test'>;
}
declare module 'react-places-autocomplete/dist/tests/utils.test.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/tests/utils.test'>;
}
declare module 'react-places-autocomplete/dist/utils.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/utils'>;
}
