// flow-typed signature: 1c88b483af27b449d93b72cd0e2a2369
// flow-typed version: <<STUB>>/react-grid-system_v3.1.2/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-grid-system'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-grid-system' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-grid-system/build/grid/Col/index' {
  declare module.exports: any;
}

declare module 'react-grid-system/build/grid/Col/style' {
  declare module.exports: any;
}

declare module 'react-grid-system/build/grid/Container/index' {
  declare module.exports: any;
}

declare module 'react-grid-system/build/grid/Container/style' {
  declare module.exports: any;
}

declare module 'react-grid-system/build/grid/Row/index' {
  declare module.exports: any;
}

declare module 'react-grid-system/build/grid/Row/style' {
  declare module.exports: any;
}

declare module 'react-grid-system/build/index' {
  declare module.exports: any;
}

declare module 'react-grid-system/build/support/RenderAny/index' {
  declare module.exports: any;
}

declare module 'react-grid-system/build/utilities/ClearFix/index' {
  declare module.exports: any;
}

declare module 'react-grid-system/build/utilities/ClearFix/style' {
  declare module.exports: any;
}

declare module 'react-grid-system/build/utilities/Hidden/index' {
  declare module.exports: any;
}

declare module 'react-grid-system/build/utilities/Hidden/style' {
  declare module.exports: any;
}

declare module 'react-grid-system/build/utilities/ScreenClassRender/index' {
  declare module.exports: any;
}

declare module 'react-grid-system/build/utilities/Visible/index' {
  declare module.exports: any;
}

declare module 'react-grid-system/build/utilities/Visible/style' {
  declare module.exports: any;
}

declare module 'react-grid-system/build/utils' {
  declare module.exports: any;
}

declare module 'react-grid-system/src/grid/Col/index' {
  declare module.exports: any;
}

declare module 'react-grid-system/src/grid/Col/style' {
  declare module.exports: any;
}

declare module 'react-grid-system/src/grid/Container/index' {
  declare module.exports: any;
}

declare module 'react-grid-system/src/grid/Container/style' {
  declare module.exports: any;
}

declare module 'react-grid-system/src/grid/Row/index' {
  declare module.exports: any;
}

declare module 'react-grid-system/src/grid/Row/style' {
  declare module.exports: any;
}

declare module 'react-grid-system/src/index' {
  declare module.exports: any;
}

declare module 'react-grid-system/src/support/RenderAny/index' {
  declare module.exports: any;
}

declare module 'react-grid-system/src/utilities/ClearFix/index' {
  declare module.exports: any;
}

declare module 'react-grid-system/src/utilities/ClearFix/style' {
  declare module.exports: any;
}

declare module 'react-grid-system/src/utilities/Hidden/index' {
  declare module.exports: any;
}

declare module 'react-grid-system/src/utilities/Hidden/style' {
  declare module.exports: any;
}

declare module 'react-grid-system/src/utilities/ScreenClassRender/index' {
  declare module.exports: any;
}

declare module 'react-grid-system/src/utilities/Visible/index' {
  declare module.exports: any;
}

declare module 'react-grid-system/src/utilities/Visible/style' {
  declare module.exports: any;
}

declare module 'react-grid-system/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-grid-system/build/grid/Col/index.js' {
  declare module.exports: $Exports<'react-grid-system/build/grid/Col/index'>;
}
declare module 'react-grid-system/build/grid/Col/style.js' {
  declare module.exports: $Exports<'react-grid-system/build/grid/Col/style'>;
}
declare module 'react-grid-system/build/grid/Container/index.js' {
  declare module.exports: $Exports<'react-grid-system/build/grid/Container/index'>;
}
declare module 'react-grid-system/build/grid/Container/style.js' {
  declare module.exports: $Exports<'react-grid-system/build/grid/Container/style'>;
}
declare module 'react-grid-system/build/grid/Row/index.js' {
  declare module.exports: $Exports<'react-grid-system/build/grid/Row/index'>;
}
declare module 'react-grid-system/build/grid/Row/style.js' {
  declare module.exports: $Exports<'react-grid-system/build/grid/Row/style'>;
}
declare module 'react-grid-system/build/index.js' {
  declare module.exports: $Exports<'react-grid-system/build/index'>;
}
declare module 'react-grid-system/build/support/RenderAny/index.js' {
  declare module.exports: $Exports<'react-grid-system/build/support/RenderAny/index'>;
}
declare module 'react-grid-system/build/utilities/ClearFix/index.js' {
  declare module.exports: $Exports<'react-grid-system/build/utilities/ClearFix/index'>;
}
declare module 'react-grid-system/build/utilities/ClearFix/style.js' {
  declare module.exports: $Exports<'react-grid-system/build/utilities/ClearFix/style'>;
}
declare module 'react-grid-system/build/utilities/Hidden/index.js' {
  declare module.exports: $Exports<'react-grid-system/build/utilities/Hidden/index'>;
}
declare module 'react-grid-system/build/utilities/Hidden/style.js' {
  declare module.exports: $Exports<'react-grid-system/build/utilities/Hidden/style'>;
}
declare module 'react-grid-system/build/utilities/ScreenClassRender/index.js' {
  declare module.exports: $Exports<'react-grid-system/build/utilities/ScreenClassRender/index'>;
}
declare module 'react-grid-system/build/utilities/Visible/index.js' {
  declare module.exports: $Exports<'react-grid-system/build/utilities/Visible/index'>;
}
declare module 'react-grid-system/build/utilities/Visible/style.js' {
  declare module.exports: $Exports<'react-grid-system/build/utilities/Visible/style'>;
}
declare module 'react-grid-system/build/utils.js' {
  declare module.exports: $Exports<'react-grid-system/build/utils'>;
}
declare module 'react-grid-system/src/grid/Col/index.jsx' {
  declare module.exports: $Exports<'react-grid-system/src/grid/Col/index'>;
}
declare module 'react-grid-system/src/grid/Col/style.js' {
  declare module.exports: $Exports<'react-grid-system/src/grid/Col/style'>;
}
declare module 'react-grid-system/src/grid/Container/index.jsx' {
  declare module.exports: $Exports<'react-grid-system/src/grid/Container/index'>;
}
declare module 'react-grid-system/src/grid/Container/style.js' {
  declare module.exports: $Exports<'react-grid-system/src/grid/Container/style'>;
}
declare module 'react-grid-system/src/grid/Row/index.jsx' {
  declare module.exports: $Exports<'react-grid-system/src/grid/Row/index'>;
}
declare module 'react-grid-system/src/grid/Row/style.js' {
  declare module.exports: $Exports<'react-grid-system/src/grid/Row/style'>;
}
declare module 'react-grid-system/src/index.js' {
  declare module.exports: $Exports<'react-grid-system/src/index'>;
}
declare module 'react-grid-system/src/support/RenderAny/index.jsx' {
  declare module.exports: $Exports<'react-grid-system/src/support/RenderAny/index'>;
}
declare module 'react-grid-system/src/utilities/ClearFix/index.jsx' {
  declare module.exports: $Exports<'react-grid-system/src/utilities/ClearFix/index'>;
}
declare module 'react-grid-system/src/utilities/ClearFix/style.js' {
  declare module.exports: $Exports<'react-grid-system/src/utilities/ClearFix/style'>;
}
declare module 'react-grid-system/src/utilities/Hidden/index.jsx' {
  declare module.exports: $Exports<'react-grid-system/src/utilities/Hidden/index'>;
}
declare module 'react-grid-system/src/utilities/Hidden/style.js' {
  declare module.exports: $Exports<'react-grid-system/src/utilities/Hidden/style'>;
}
declare module 'react-grid-system/src/utilities/ScreenClassRender/index.jsx' {
  declare module.exports: $Exports<'react-grid-system/src/utilities/ScreenClassRender/index'>;
}
declare module 'react-grid-system/src/utilities/Visible/index.jsx' {
  declare module.exports: $Exports<'react-grid-system/src/utilities/Visible/index'>;
}
declare module 'react-grid-system/src/utilities/Visible/style.js' {
  declare module.exports: $Exports<'react-grid-system/src/utilities/Visible/style'>;
}
declare module 'react-grid-system/src/utils.js' {
  declare module.exports: $Exports<'react-grid-system/src/utils'>;
}
