// flow-typed signature: f0739daa928bf7696f82118a13372daf
// flow-typed version: <<STUB>>/webpack-closure-compiler_v^2.1.6/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-closure-compiler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-closure-compiler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-closure-compiler/lib/js_runner' {
  declare module.exports: any;
}

declare module 'webpack-closure-compiler/lib/runner' {
  declare module.exports: any;
}

declare module 'webpack-closure-compiler/lib/utils' {
  declare module.exports: any;
}

declare module 'webpack-closure-compiler/test/bundle-js' {
  declare module.exports: any;
}

declare module 'webpack-closure-compiler/test/bundle' {
  declare module.exports: any;
}

declare module 'webpack-closure-compiler/test/entry' {
  declare module.exports: any;
}

declare module 'webpack-closure-compiler/test/externs' {
  declare module.exports: any;
}

declare module 'webpack-closure-compiler/test/webpack.config-js' {
  declare module.exports: any;
}

declare module 'webpack-closure-compiler/test/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-closure-compiler/index' {
  declare module.exports: $Exports<'webpack-closure-compiler'>;
}
declare module 'webpack-closure-compiler/index.js' {
  declare module.exports: $Exports<'webpack-closure-compiler'>;
}
declare module 'webpack-closure-compiler/lib/js_runner.js' {
  declare module.exports: $Exports<'webpack-closure-compiler/lib/js_runner'>;
}
declare module 'webpack-closure-compiler/lib/runner.js' {
  declare module.exports: $Exports<'webpack-closure-compiler/lib/runner'>;
}
declare module 'webpack-closure-compiler/lib/utils.js' {
  declare module.exports: $Exports<'webpack-closure-compiler/lib/utils'>;
}
declare module 'webpack-closure-compiler/test/bundle-js.js' {
  declare module.exports: $Exports<'webpack-closure-compiler/test/bundle-js'>;
}
declare module 'webpack-closure-compiler/test/bundle.js' {
  declare module.exports: $Exports<'webpack-closure-compiler/test/bundle'>;
}
declare module 'webpack-closure-compiler/test/entry.js' {
  declare module.exports: $Exports<'webpack-closure-compiler/test/entry'>;
}
declare module 'webpack-closure-compiler/test/externs.js' {
  declare module.exports: $Exports<'webpack-closure-compiler/test/externs'>;
}
declare module 'webpack-closure-compiler/test/webpack.config-js.js' {
  declare module.exports: $Exports<'webpack-closure-compiler/test/webpack.config-js'>;
}
declare module 'webpack-closure-compiler/test/webpack.config.js' {
  declare module.exports: $Exports<'webpack-closure-compiler/test/webpack.config'>;
}
