const types = {
    'USER_CREATE_OBJECT': 'USER_CREATE_OBJECT',
    'USER_SAVE_OBJECT': 'USER_SAVE_OBJECT',
    'USER_NEW_OBJECT': 'USER_NEW_OBJECT',
    'USER_UPDATE_OBJECT': 'USER_UPDATE_OBJECT',
    'USER_DELETE_OBJECT': 'USER_DELETE_OBJECT',
    'USER_GET_OBJECT': 'USER_GET_OBJECT',
    'USER_GET_OBJECTS': 'USER_GET_OBJECTS',
    'USER_INPUT_CHANGED': 'USER_INPUT_CHANGED',
    'USER_LOADING': 'USER_LOADING',
    'USER_ERROR': 'USER_ERROR',
    'USER_VALID': 'USER_VALID',
    'USER_LOADING_CACHE': 'USER_LOADING_CACHE',
    'USER_LOADING_ONLINE': 'USER_LOADING_ONLINE'
};

export default types;