// flow-typed signature: c620af739f51c3a5bff920f605e9a0f0
// flow-typed version: <<STUB>>/@fnando/cnpj_v^0.1.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fnando/cnpj'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fnando/cnpj' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@fnando/cnpj/dist/cnpj' {
  declare module.exports: any;
}

declare module '@fnando/cnpj/dist/cnpj.min' {
  declare module.exports: any;
}

declare module '@fnando/cnpj/dist/node' {
  declare module.exports: any;
}

declare module '@fnando/cnpj/src/cnpj' {
  declare module.exports: any;
}

// Filename aliases
declare module '@fnando/cnpj/dist/cnpj.js' {
  declare module.exports: $Exports<'@fnando/cnpj/dist/cnpj'>;
}
declare module '@fnando/cnpj/dist/cnpj.min.js' {
  declare module.exports: $Exports<'@fnando/cnpj/dist/cnpj.min'>;
}
declare module '@fnando/cnpj/dist/node.js' {
  declare module.exports: $Exports<'@fnando/cnpj/dist/node'>;
}
declare module '@fnando/cnpj/src/cnpj.js' {
  declare module.exports: $Exports<'@fnando/cnpj/src/cnpj'>;
}
