// flow-typed signature: e6a025ebbe0b1f2ae69018cb85df45f5
// flow-typed version: <<STUB>>/@fnando/cpf_v^0.1.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fnando/cpf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fnando/cpf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@fnando/cpf/dist/cpf' {
  declare module.exports: any;
}

declare module '@fnando/cpf/dist/cpf.min' {
  declare module.exports: any;
}

declare module '@fnando/cpf/dist/node' {
  declare module.exports: any;
}

declare module '@fnando/cpf/spec/cpf.spec' {
  declare module.exports: any;
}

declare module '@fnando/cpf/src/cpf' {
  declare module.exports: any;
}

declare module '@fnando/cpf/webpack.config' {
  declare module.exports: any;
}

declare module '@fnando/cpf/webpack.config.node' {
  declare module.exports: any;
}

// Filename aliases
declare module '@fnando/cpf/dist/cpf.js' {
  declare module.exports: $Exports<'@fnando/cpf/dist/cpf'>;
}
declare module '@fnando/cpf/dist/cpf.min.js' {
  declare module.exports: $Exports<'@fnando/cpf/dist/cpf.min'>;
}
declare module '@fnando/cpf/dist/node.js' {
  declare module.exports: $Exports<'@fnando/cpf/dist/node'>;
}
declare module '@fnando/cpf/spec/cpf.spec.js' {
  declare module.exports: $Exports<'@fnando/cpf/spec/cpf.spec'>;
}
declare module '@fnando/cpf/src/cpf.js' {
  declare module.exports: $Exports<'@fnando/cpf/src/cpf'>;
}
declare module '@fnando/cpf/webpack.config.js' {
  declare module.exports: $Exports<'@fnando/cpf/webpack.config'>;
}
declare module '@fnando/cpf/webpack.config.node.js' {
  declare module.exports: $Exports<'@fnando/cpf/webpack.config.node'>;
}
